name: Build TWRP Joy 4

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Dọn dẹp không gian ổ đĩa (Quan trọng)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Cài đặt công cụ build
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 rsync

    - name: Cài đặt công cụ Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Khởi tạo nguồn TWRP (Minimal Manifest)
      run: |
        mkdir work
        cd work
        git config --global user.name "Your Name"
        git config --global user.email "you@example.com"
        repo init --depth=1 -u https://github.com/minimal-twrp/android_bootable_recovery.git -b android-11
        repo sync -j$(nproc) --force-sync

    - name: Clone Device Tree
      run: |
        cd work
        git clone https://github.com/long266/twrp_device_vsmart_willowpro -b main device/vsmart/willowpro

    - name: Bắt đầu Build
      run: |
        cd work
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_willowpro-eng
        mka recoveryimage -j$(nproc)

    - name: Upload kết quả (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Vsmart-Joy4
        path: work/out/target/product/willowpro/*.img
